// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sixvu.security;

import com.sixvu.security.PersistentLoginsDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersistentLoginsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PersistentLoginsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PersistentLoginsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private PersistentLoginsDataOnDemand PersistentLoginsIntegrationTest.dod;
    
    @Test
    public void PersistentLoginsIntegrationTest.testCountPersistentLoginses() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", dod.getRandomPersistentLogins());
        long count = com.sixvu.security.PersistentLogins.countPersistentLoginses();
        org.junit.Assert.assertTrue("Counter for 'PersistentLogins' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PersistentLoginsIntegrationTest.testFindPersistentLogins() {
        com.sixvu.security.PersistentLogins obj = dod.getRandomPersistentLogins();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to provide an identifier", id);
        obj = com.sixvu.security.PersistentLogins.findPersistentLogins(id);
        org.junit.Assert.assertNotNull("Find method for 'PersistentLogins' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PersistentLogins' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PersistentLoginsIntegrationTest.testFindAllPersistentLoginses() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", dod.getRandomPersistentLogins());
        long count = com.sixvu.security.PersistentLogins.countPersistentLoginses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PersistentLogins', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sixvu.security.PersistentLogins> result = com.sixvu.security.PersistentLogins.findAllPersistentLoginses();
        org.junit.Assert.assertNotNull("Find all method for 'PersistentLogins' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PersistentLogins' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PersistentLoginsIntegrationTest.testFindPersistentLoginsEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", dod.getRandomPersistentLogins());
        long count = com.sixvu.security.PersistentLogins.countPersistentLoginses();
        if (count > 20) count = 20;
        java.util.List<com.sixvu.security.PersistentLogins> result = com.sixvu.security.PersistentLogins.findPersistentLoginsEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PersistentLogins' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PersistentLogins' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void PersistentLoginsIntegrationTest.testFlush() {
        com.sixvu.security.PersistentLogins obj = dod.getRandomPersistentLogins();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to provide an identifier", id);
        obj = com.sixvu.security.PersistentLogins.findPersistentLogins(id);
        org.junit.Assert.assertNotNull("Find method for 'PersistentLogins' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPersistentLogins(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PersistentLogins' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void PersistentLoginsIntegrationTest.testMerge() {
        com.sixvu.security.PersistentLogins obj = dod.getRandomPersistentLogins();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to provide an identifier", id);
        obj = com.sixvu.security.PersistentLogins.findPersistentLogins(id);
        boolean modified =  dod.modifyPersistentLogins(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PersistentLogins' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void PersistentLoginsIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", dod.getRandomPersistentLogins());
        com.sixvu.security.PersistentLogins obj = dod.getNewTransientPersistentLogins(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PersistentLogins' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PersistentLogins' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void PersistentLoginsIntegrationTest.testRemove() {
        com.sixvu.security.PersistentLogins obj = dod.getRandomPersistentLogins();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PersistentLogins' failed to provide an identifier", id);
        obj = com.sixvu.security.PersistentLogins.findPersistentLogins(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PersistentLogins' with identifier '" + id + "'", com.sixvu.security.PersistentLogins.findPersistentLogins(id));
    }
    
}
