// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sixvu.domain;

import com.sixvu.domain.Person;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersonDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PersonDataOnDemand: @Component;
    
    private Random PersonDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Person> PersonDataOnDemand.data;
    
    public Person PersonDataOnDemand.getNewTransientPerson(int index) {
        com.sixvu.domain.Person obj = new com.sixvu.domain.Person();
        obj.setAuthority(com.sixvu.types.Authority.class.getEnumConstants()[0]);
        obj.setBirthDate(new java.util.Date());
        java.lang.String country = "_" + index;
        if (country.length() > 2) {
            country  = country.substring(0, 2);
        }
        obj.setCountry(country);
        java.lang.String email = "email_" + index;
        if (email.length() > 255) {
            email  = email.substring(0, 255);
        }
        obj.setEmail(email);
        obj.setGender(com.sixvu.types.Gender.class.getEnumConstants()[0]);
        java.lang.String passWord = "passWord_" + index;
        if (passWord.length() > 32) {
            passWord  = passWord.substring(0, 32);
        }
        obj.setPassWord(passWord);
        java.lang.String paypalEmail = "paypalEmail_" + index;
        if (paypalEmail.length() > 255) {
            paypalEmail  = paypalEmail.substring(0, 255);
        }
        obj.setPaypalEmail(paypalEmail);
        obj.setStatus(com.sixvu.types.Enabled.class.getEnumConstants()[0]);
        java.lang.String userName = "userName_" + index;
        if (userName.length() > 32) {
            userName  = userName.substring(0, 32);
        }
        obj.setUserName(userName);
        return obj;
    }
    
    public Person PersonDataOnDemand.getSpecificPerson(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Person obj = data.get(index);
        return Person.findPerson(obj.getId());
    }
    
    public Person PersonDataOnDemand.getRandomPerson() {
        init();
        Person obj = data.get(rnd.nextInt(data.size()));
        return Person.findPerson(obj.getId());
    }
    
    public boolean PersonDataOnDemand.modifyPerson(Person obj) {
        return false;
    }
    
    @Transactional(propagation = Propagation.REQUIRES_NEW)
    public void PersonDataOnDemand.init() {
        if (data != null && !data.isEmpty()) {
            return;
        }
        
        data = com.sixvu.domain.Person.findPersonEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Person' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.sixvu.domain.Person>();
        for (int i = 0; i < 10; i++) {
            com.sixvu.domain.Person obj = getNewTransientPerson(i);
            obj.persist();
            data.add(obj);
        }
    }
    
}
