// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sixvu.domain;

import com.sixvu.domain.VideoDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VideoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VideoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VideoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private VideoDataOnDemand VideoIntegrationTest.dod;
    
    @Test
    public void VideoIntegrationTest.testCountVideos() {
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        long count = com.sixvu.domain.Video.countVideos();
        org.junit.Assert.assertTrue("Counter for 'Video' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VideoIntegrationTest.testFindVideo() {
        com.sixvu.domain.Video obj = dod.getRandomVideo();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = com.sixvu.domain.Video.findVideo(id);
        org.junit.Assert.assertNotNull("Find method for 'Video' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Video' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VideoIntegrationTest.testFindAllVideos() {
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        long count = com.sixvu.domain.Video.countVideos();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Video', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.sixvu.domain.Video> result = com.sixvu.domain.Video.findAllVideos();
        org.junit.Assert.assertNotNull("Find all method for 'Video' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Video' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VideoIntegrationTest.testFindVideoEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        long count = com.sixvu.domain.Video.countVideos();
        if (count > 20) count = 20;
        java.util.List<com.sixvu.domain.Video> result = com.sixvu.domain.Video.findVideoEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Video' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Video' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    @Transactional
    public void VideoIntegrationTest.testFlush() {
        com.sixvu.domain.Video obj = dod.getRandomVideo();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = com.sixvu.domain.Video.findVideo(id);
        org.junit.Assert.assertNotNull("Find method for 'Video' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVideo(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Video' failed to increment on flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void VideoIntegrationTest.testMerge() {
        com.sixvu.domain.Video obj = dod.getRandomVideo();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = com.sixvu.domain.Video.findVideo(id);
        boolean modified =  dod.modifyVideo(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.merge();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Video' failed to increment on merge and flush directive", obj.getVersion() > currentVersion || !modified);
    }
    
    @Test
    @Transactional
    public void VideoIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", dod.getRandomVideo());
        com.sixvu.domain.Video obj = dod.getNewTransientVideo(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Video' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Video' identifier to no longer be null", obj.getId());
    }
    
    @Test
    @Transactional
    public void VideoIntegrationTest.testRemove() {
        com.sixvu.domain.Video obj = dod.getRandomVideo();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Video' failed to provide an identifier", id);
        obj = com.sixvu.domain.Video.findVideo(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Video' with identifier '" + id + "'", com.sixvu.domain.Video.findVideo(id));
    }
    
}
